name: CI

on:
  pull_request: ~
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  cs:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2

      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Install ecs
          run: cd tools/ecs && composer update --no-interaction --no-suggest

      -   name: Run the CS fixer
          run: composer cs-fixer

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
            coverage: none
          env:
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -   name: Checkout
          uses: actions/checkout@v3

      -   name: Install the dependencies
          run: |
            composer update --no-interaction --no-progress
            cd tools/phpstan && composer update --no-interaction --no-suggest
      -   name: Run PHPStan
          run: composer phpstan

  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2 ]
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Install phpunit
          run: cd tools/phpunit && composer update --no-interaction --no-suggest

      -   name: Install the dependencies
          run: composer update --no-interaction --no-suggest

      -   name: Run the unit tests
          run: composer unit-tests

  prefer-lowest-tests:
    name: PHP ${{ matrix.php }} --prefer-lowest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2 ]
    steps:
      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Install phpunit
          run: cd tools/phpunit && composer update --no-interaction --no-suggest

      -   name: Install the dependencies
          run: composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest

      -   name: Run the unit tests
          run: composer unit-tests
